### ISSUE TITLE
add `npm token` input

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/solidity-workflows#12]
```yaml
on:
    workflow_call:
      secrets:
        node_auth_token:
          description: 'NPM token'
          required: true
```

https://github.com/The-Poolz/solidity-workflows/blob/cb1139b1c27b6a934ddabffd6a81d393233c5c69/.github/workflows/release.yml#L37
